language: php

php: [5.3.3, 5.3, 5.4, 5.5, hhvm]

before_script:
  - composer install --prefer-source
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - bin/phpspec run --format=pretty
  - bin/behat --format=pretty
